[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wyoming-upperair"
version = "0.1.1"
description = "Download University of Wyoming upper-air sounding data directly into CSV files."
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Tejas Kalia" }
]

license = "MIT"
license-files = ["LICENSE"]

dependencies = [
    "pandas>=2.0",
    "requests>=2.31"
]

keywords = [
    "weather",
    "meteorology",
    "upper-air",
    "upperair",
    "radiosonde",
    "sounding",
    "wyoming",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/ProHackerz669/wyoming-upperair"
Repository = "https://github.com/ProHackerz669/wyoming-upperair"
Issues = "https://github.com/ProHackerz669/wyoming-upperair/issues"

[project.optional-dependencies]
test = [
    "pytest>=8"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]